// 🌊 this file is auto-generated by 404 Software's script. don't edit it.
// https://404-software.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
const CrossSolid = (props: SvgProps) => <Svg width={24} height={24} viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><Path d="M8.46445 15.5355L15.5355 8.46446" stroke="black" strokeWidth={1.5} strokeLinecap="round" /><Path d="M8.46446 8.46447L15.5355 15.5355" stroke="black" strokeWidth={1.5} strokeLinecap="round" /></Svg>;
export default CrossSolid;