// 🌊 this file is auto-generated by 404 Software's script. don't edit it.
// https://404-software.com
import * as React from "react";
import Svg, { SvgProps, Rect, Path } from "react-native-svg";
const MusicSolid = (props: SvgProps) => <Svg width={24} height={24} viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><Rect x={5} y={14} width={7} height={7} rx={3.5} fill="black" stroke="black" strokeWidth={1.5} /><Path d="M12 17L12 5" stroke="black" strokeWidth={1.5} strokeLinecap="round" /><Path d="M12 3H18C19.1046 3 20 3.89543 20 5V5V5C20 6.10457 19.1046 7 18 7H12V5V3Z" fill="black" stroke="black" strokeWidth={1.5} strokeLinejoin="round" /></Svg>;
export default MusicSolid;