// 🌊 this file is auto-generated by 404 Software's script. don't edit it.
// https://404-software.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
const PlusSolid = (props: SvgProps) => <Svg width={24} height={24} viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><Path d="M12 17V7" stroke="black" strokeWidth={1.5} strokeLinecap="round" /><Path d="M7 12L17 12" stroke="black" strokeWidth={1.5} strokeLinecap="round" /></Svg>;
export default PlusSolid;