// 🌊 this file is auto-generated by 404 Software's script. don't edit it.
// https://404-software.com
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
const WindowsSolid = (props: SvgProps) => <Svg width={24} height={24} viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" {...props}><Path d="M20.4796 10.5071H13.0265V5.12189L20.4796 3.88686V10.5071ZM20.4796 13.4953V20.1133L13.0265 18.8998V13.4953H20.4796ZM9.63278 10.5047H3.56482V6.62191L9.63278 5.61653V10.5047ZM9.63278 13.4953V18.4117L3.56482 17.4233V13.4953H9.63278Z" fill="black" stroke="black" strokeWidth={1.5} strokeLinejoin="round" /></Svg>;
export default WindowsSolid;